import tkinter
window = tkinter.Tk()
window.geometry("400x400")
window.title("Log In Maidonian")
lbl = tkinter.Label(window, text="Maidonian Username",fg = "red", font = ("Metal Lord", 15))
lbl.pack()
ent = tkinter.Entry(window)
ent.pack()
lbl = tkinter.Label(window, text="Maidonian Password",fg = "red", font = ("Metal Lord", 15))
lbl.pack()
ent = tkinter.Entry(window)
ent.pack()
btn = tkinter.Button(window, text="Up The Irons", bg="red" ,fg="black", font= ("Metal Lord",10))
btn.pack()
window.mqinloop()
