import tkinter  
window = tkinter.Tk()
lbl = tkinter.Label(window,text= "Enter First Number")
lbl.grid(row=0,column=0)
txt = tkinter.Entry(window,width=10)
txt.grid(row=0,column=1)
lbl2 = tkinter.Label(window,text="Enter Second Number")
lbl2.grid(row=1,column=0)
txt2 = tkinter.Entry(window,width=10)
txt2.grid(row=1,column=1)
lbl3=tkinter.Label(window,)
lbl3.grid(row=2,column=1)
lbl4=tkinter.Label(window,text="Your Result Is:")
lbl4.grid(row=2,column=0)
def clicked():
    a=int(txt.get())+int(txt2.get())
    lbl3.configure(text=a)
btn=tkinter.Button(window, text="Press For Results", command=clicked)
btn.grid(row=3,column=1)
window.mainloop()
